import type { BlogPost } from '@/lib/blog/types'

export const blogPosts: BlogPost[] = [
  {
    slug: 'screen-free-activities-for-3-year-olds',
    title: '27 Screen-Free Activities for 3-Year-Olds (No Prep, No Fancy Supplies)',
    excerpt:
      'Simple sensory, movement, language, and fine-motor activities that take only a few minutes to set up.',
    seoDescription:
      'Try 27 easy screen-free activities for 3-year-olds using everyday supplies, organized by sensory play, movement, language, and fine motor skills.',
    category: 'Screen-Free Play',
    date: '2026-09-23',
    heroImage: '',
    heroImageAlt: '',
    seoKeywords: [
      'screen free activities for 3 year olds',
      'activities for 3 year olds at home',
      'no prep preschool activities',
    ],
    blocks: [
      { type: 'paragraph', content: 'A good activity for a 3-year-old does not need an elaborate setup. At this age, pouring, sorting, pretending, moving, and talking are the work of learning. The best screen-free ideas are short, flexible, and easy to repeat.' },
      { type: 'callout', tone: 'tip', content: 'Choose one idea, set it up in two minutes or less, and let your child decide how long to stay with it. Ten focused minutes is a win.' },
      { type: 'heading', content: 'Sensory activities' },
      { type: 'list', ordered: true, items: [
        'Scoop dry oats between two bowls with a spoon.',
        'Wash plastic animals in a bowl of warm, soapy water.',
        'Make play-dough snakes, balls, and pretend food.',
        'Hide large blocks under a towel and identify them by touch.',
        'Paint water onto the sidewalk with a wide brush.',
        'Sort pom-poms or large bottle caps by color.',
      ] },
      { type: 'heading', content: 'Movement activities' },
      { type: 'list', ordered: true, items: [
        'Walk like five animals: stomp, waddle, hop, crawl, and slither.',
        'Make a masking-tape line and balance from one end to the other.',
        'Toss rolled-up socks into a laundry basket.',
        'Freeze when the music stops and wiggle when it starts.',
        'Build a pillow path across the floor.',
        'Copy a simple movement pattern: clap, clap, jump.',
        'Carry a stuffed animal through a homemade obstacle course.',
      ] },
      { type: 'heading', content: 'Language and pretend-play activities' },
      { type: 'list', ordered: true, items: [
        'Pack a pretend picnic and name each item.',
        'Tell a three-part story using three toys.',
        'Play restaurant with paper menus and toy food.',
        'Go on a household color hunt.',
        'Describe an object without naming it and let your child guess.',
        'Look through a picture book and invent a new ending.',
        'Call a family member on a pretend phone and practice conversation.',
      ] },
      { type: 'heading', content: 'Fine-motor and quiet-time activities' },
      { type: 'list', ordered: true, items: [
        'Thread large pasta tubes onto a shoelace.',
        'Peel and place reusable stickers on paper.',
        'Tear colored paper and glue the pieces into a collage.',
        'Move cotton balls with kitchen tongs.',
        'Match socks from a clean laundry pile.',
        'Build the tallest possible block tower.',
        'Draw roads for toy cars with chunky crayons.',
      ] },
      { type: 'paragraph', content: 'Three-year-olds learn through repetition, so favorite activities can come back every week with one small change. Switch the objects, add a new color, or invite your child to explain the rules to you.' },
      { type: 'CTA', heading: 'Want the next activity ready for you?', content: 'Get a free sample Kiddle with playful, printable activities for ages 3–5.', buttonLabel: 'Get the Free Sample', href: '/#sample-kiddle' },
    ],
  },
  {
    slug: 'screen-free-activities-for-4-year-olds',
    title: '30 Screen-Free Activities for 4-Year-Olds That Actually Hold Their Attention',
    excerpt:
      'Hands-on ideas with enough challenge, movement, and imagination to keep a busy 4-year-old interested.',
    seoDescription:
      'Discover 30 engaging screen-free activities for 4-year-olds, including movement games, pretend play, art, science, and quiet-time ideas.',
    category: 'Screen-Free Play',
    date: '2026-09-22',
    heroImage: '',
    heroImageAlt: '',
    seoKeywords: [
      'screen free activities for 4 year olds',
      'activities for 4 year olds at home',
      'preschool activities without screens',
    ],
    blocks: [
      { type: 'paragraph', content: 'Four-year-olds often stay engaged longer when an activity has a goal, a story, or a surprising next step. Instead of asking them to simply color, invite them to design a treasure map, follow it, and explain where the treasure is hidden.' },
      { type: 'callout', tone: 'tip', content: 'To stretch an activity, add layers: make it, test it, change it, then tell someone about it.' },
      { type: 'heading', content: 'Build and invent' },
      { type: 'list', ordered: true, items: [
        'Build a bridge for a toy car using blocks and cardboard.',
        'Create a blanket fort with a reading corner.',
        'Design a paper airplane and test three throws.',
        'Make a marble-free maze for a pom-pom and blow it through with a straw.',
        'Build a home for a stuffed animal from a small box.',
        'Invent a machine from clean recycling materials.',
      ] },
      { type: 'heading', content: 'Move and play' },
      { type: 'list', ordered: true, items: [
        'Follow a five-step indoor obstacle course.',
        'Play red light, green light with animal movements.',
        'Try a balloon keep-up challenge.',
        'Make movement cards and pick one at random.',
        'Go on a shape hunt around the house.',
        'Create a hopscotch path with removable tape.',
      ] },
      { type: 'heading', content: 'Imagine and tell stories' },
      { type: 'list', ordered: true, items: [
        'Draw a treasure map and lead someone to the prize.',
        'Run a pretend post office and deliver notes.',
        'Put on a puppet show with paper-bag characters.',
        'Turn a cardboard box into a shop, spaceship, or bus.',
        'Choose three random objects and tell a story that uses all three.',
        'Make up a new verse for a familiar song.',
      ] },
      { type: 'heading', content: 'Think, create, and experiment' },
      { type: 'list', ordered: true, items: [
        'Sort household objects by material, size, or purpose.',
        'Predict which safe objects will sink or float, then test them.',
        'Mix primary paint colors and name the new colors.',
        'Continue a bead, block, or sticker pattern.',
        'Cut paper strips and turn them into a chain.',
        'Draw the same object from the front and the side.',
        'Make a simple weather chart for the week.',
        'Match uppercase letters to lowercase letters.',
        'Count out snacks into groups of two, three, and four.',
        'Complete a homemade picture scavenger hunt.',
        'Copy a block structure, then invent a harder one.',
        'Draw a comic with a beginning, middle, and end.',
      ] },
      { type: 'paragraph', content: 'If attention starts to fade, ask one useful question: “What should happen next?” Giving a 4-year-old ownership often works better than adding more instructions.' },
      { type: 'CTA', heading: 'Make screen-free time easier every week', content: 'Try a free sample of The Kiddle’s ready-to-print activities for ages 3–5.', buttonLabel: 'Send Me a Free Sample', href: '/#sample-kiddle' },
    ],
  },
  {
    slug: 'screen-free-activities-for-5-year-olds',
    title: '25 Screen-Free Activities for 5-Year-Olds (Beyond Coloring Pages)',
    excerpt:
      'Puzzles, challenges, experiments, and creative projects for children ready to think a little deeper.',
    seoDescription:
      'Explore 25 screen-free activities for 5-year-olds with logic games, science experiments, storytelling, movement, and real-world challenges.',
    category: 'Screen-Free Play',
    date: '2026-09-21',
    heroImage: '',
    heroImageAlt: '',
    seoKeywords: [
      'screen free activities for 5 year olds',
      'activities for 5 year olds without screens',
      'learning activities for 5 year olds',
    ],
    blocks: [
      { type: 'paragraph', content: 'At 5, many children want a real problem to solve. They still love art and pretend play, but they are increasingly ready to plan, predict, record, and revise. These ideas give them a challenge without making play feel like homework.' },
      { type: 'heading', content: 'Logic and problem-solving' },
      { type: 'list', ordered: true, items: [
        'Create a three-clue treasure hunt.',
        'Copy a block design, then rebuild it from memory.',
        'Sort objects in two different ways and explain each rule.',
        'Make a repeating movement pattern for someone else to follow.',
        'Solve a homemade “which one does not belong?” picture puzzle.',
        'Plan the shortest route through a room without touching the floor.',
      ] },
      { type: 'heading', content: 'Real science and observation' },
      { type: 'list', ordered: true, items: [
        'Test which paper shape makes the strongest bridge.',
        'Predict and test what will sink or float.',
        'Sprout a bean in a damp paper towel and sketch the changes.',
        'Mix colors and create a labeled color chart.',
        'Build a foil boat and count how many coins it can hold.',
        'Compare which ice cube melts fastest in three locations.',
      ] },
      { type: 'heading', content: 'Stories, words, and creativity' },
      { type: 'list', ordered: true, items: [
        'Draw a six-panel comic.',
        'Create a menu for a pretend restaurant.',
        'Make a tiny book with a cover, title, and author name.',
        'Write or draw clues for a family guessing game.',
        'Retell a familiar story from another character’s point of view.',
        'Design a new animal and explain its habitat.',
        'Make a rhyming-word chain.',
      ] },
      { type: 'heading', content: 'Movement and real-life challenges' },
      { type: 'list', ordered: true, items: [
        'Measure a room in footsteps and compare results.',
        'Create and teach a five-move dance.',
        'Follow a picture recipe for a simple snack with adult help.',
        'Plan and pack a pretend day trip.',
        'Set up a timed sock-sorting challenge.',
        'Invent a playground game and explain the rules.',
      ] },
      { type: 'callout', tone: 'info', content: 'The goal is not a perfect result. Planning, testing, and changing an idea are the valuable parts.' },
      { type: 'CTA', heading: 'Give your 5-year-old a fresh challenge', content: 'Get a free Kiddle sample with puzzles, experiments, stories, and hands-on play.', buttonLabel: 'Get the Free Sample', href: '/#sample-kiddle' },
    ],
  },
  {
    slug: 'fine-motor-activities-for-3-year-olds',
    title: '15 Fine Motor Activities for 3-Year-Olds (That Don’t Feel Like Homework)',
    excerpt:
      'Playful ways to practice grasping, pinching, threading, turning, and cutting with everyday materials.',
    seoDescription:
      'Build hand strength and coordination with 15 playful fine motor activities for 3-year-olds using simple household and craft materials.',
    category: 'Skill Building',
    date: '2026-09-20',
    heroImage: '',
    heroImageAlt: '',
    seoKeywords: [
      'fine motor activities for 3 year olds',
      'hand strengthening activities for preschoolers',
      'preschool cutting and tracing practice',
    ],
    blocks: [
      { type: 'paragraph', content: 'Fine motor skills are the small hand and finger movements children use for dressing, drawing, eating, turning pages, and eventually writing. At age 3, practice should feel like play—not a test of how neatly a child can finish a worksheet.' },
      { type: 'callout', tone: 'note', content: 'Children develop at different rates. These ideas are for everyday play, not diagnosis or therapy. Ask a pediatrician or occupational therapist if you have concerns about your child’s development.' },
      { type: 'heading', content: '15 playful fine-motor ideas' },
      { type: 'list', ordered: true, items: [
        'Pinch and roll play dough into pretend food.',
        'Move cotton balls between bowls with kitchen tongs.',
        'Thread large pasta tubes onto a shoelace.',
        'Peel reusable stickers and build a picture.',
        'Tear paper into pieces for a collage.',
        'Open and close clothespins around a cardboard edge.',
        'Scoop and pour dry oats with small cups and spoons.',
        'Push pipe cleaners through holes in a colander.',
        'Turn nuts onto large toy bolts.',
        'Use an eyedropper to move colored water between cups.',
        'Wrap rubber bands around a sturdy container.',
        'Trace wide roads and paths with a chunky crayon.',
        'Snip short paper strips with child-safe scissors and close supervision.',
        'Build small towers with interlocking blocks.',
        'Fasten and unfasten large buttons on an old shirt or dressing frame.',
      ] },
      { type: 'heading', content: 'How to keep practice frustration-free' },
      { type: 'paragraph', content: 'Start with larger objects, model the motion once, and allow plenty of time. If a task is frustrating, make it easier or return to it another day. Five cheerful minutes builds more confidence than twenty pressured ones.' },
      { type: 'CTA', heading: 'Ready for playful pencil-and-scissor practice?', content: 'Try a free Kiddle sample designed to mix skill building with stories, puzzles, and fun.', buttonLabel: 'Try a Free Sample', href: '/#sample-kiddle' },
    ],
  },
  {
    slug: 'screen-time-alternatives-for-preschoolers',
    title: 'Tired of the Tablet? 20 Screen-Time Alternatives for Preschoolers',
    excerpt:
      'Realistic, low-prep ideas for the moments when a child asks for one more show and a parent needs an easy next step.',
    seoDescription:
      'Find 20 realistic screen-time alternatives for preschoolers, with quick ideas for independent play, connection, movement, and calm-down time.',
    category: 'Screen-Free Play',
    date: '2026-09-19',
    heroImage: '',
    heroImageAlt: '',
    seoKeywords: [
      'screen time alternatives for preschoolers',
      'alternatives to tablets for kids',
      'screen free preschool activities',
    ],
    blocks: [
      { type: 'paragraph', content: 'Screens are useful, and using them does not make anyone a bad parent. The difficult part is often the transition: the show ends, the tablet goes away, and nobody knows what comes next. A short list of ready choices can make that moment much calmer.' },
      { type: 'heading', content: 'When you need five minutes to start dinner' },
      { type: 'list', items: [
        'Sticker scene on a blank sheet of paper.',
        'Toy-animal washing station with a towel underneath.',
        'Sock matching from a small laundry pile.',
        'Play-dough bakery with a tray and spoon.',
        'Picture-book basket in a cozy corner.',
      ] },
      { type: 'heading', content: 'When your child needs to move' },
      { type: 'list', items: [
        'Animal walk from one room to another.',
        'Balloon keep-up challenge.',
        'Three-song dance party.',
        'Pillow obstacle course.',
        'Indoor scavenger hunt for five colors.',
      ] },
      { type: 'heading', content: 'When you can play together' },
      { type: 'list', items: [
        'Build a fort and read one story inside.',
        'Draw a neighborhood map together.',
        'Make up a story using three household objects.',
        'Try a sink-or-float experiment at the kitchen sink.',
        'Prepare a simple snack from a picture sequence.',
      ] },
      { type: 'heading', content: 'When everyone needs to slow down' },
      { type: 'list', items: [
        'Listen to an audiobook while drawing.',
        'Complete a simple puzzle.',
        'Sort buttons, blocks, or cards by color.',
        'Make a paper collage.',
        'Look through family photos and tell the story behind each one.',
      ] },
      { type: 'callout', tone: 'tip', content: 'Instead of asking “What do you want to do?”, offer two concrete choices: “Would you like play dough or a scavenger hunt?”' },
      { type: 'paragraph', content: 'A repeatable rhythm helps more than an endless supply of new ideas. Keep two or three favorite activities ready, rotate them through the week, and use a printable pack when you need a fresh option without more planning.' },
      { type: 'CTA', heading: 'Make the next screen-free moment simpler', content: 'Get a free sample Kiddle and keep a ready-to-print activity on hand.', buttonLabel: 'Email Me a Free Sample', href: '/#sample-kiddle' },
    ],
  },
  {
    slug: 'indoor-activities-for-4-year-olds-without-screen',
    title: 'Indoor Activities for 4-Year-Olds (No Screen Required)',
    excerpt:
      'Fast-start activities for stuck-inside days, from energy burners to calm puzzles and pretend play.',
    seoDescription:
      'Try 18 easy indoor activities for 4-year-olds without screens, including movement, quiet-time, creative, and learning ideas.',
    category: 'Indoor Play',
    date: '2026-09-18',
    heroImage: '',
    heroImageAlt: '',
    seoKeywords: [
      'indoor activities for 4 year olds without screen',
      'indoor activities for preschoolers',
      'no screen activities for kids at home',
    ],
    blocks: [
      { type: 'paragraph', content: 'Stuck-inside days go better when you can alternate big movement with something calm. Every idea below uses common household materials and can begin in about a minute.' },
      { type: 'heading', content: 'Burn some energy' },
      { type: 'list', ordered: true, items: [
        'Make a pillow-and-tape obstacle course.',
        'Copy animal walks from room to room.',
        'Keep a balloon off the floor.',
        'Play freeze dance for three songs.',
        'Toss rolled-up socks into baskets at different distances.',
        'Follow a movement pattern: clap, stomp, spin, freeze.',
      ] },
      { type: 'heading', content: 'Settle into quiet play' },
      { type: 'list', ordered: true, items: [
        'Build a blanket reading nook.',
        'Complete a homemade matching game.',
        'Sort small collections by color or size.',
        'Draw a road map for toy vehicles.',
        'Make a picture with reusable stickers.',
        'Listen to a story and draw a favorite part.',
      ] },
      { type: 'heading', content: 'Create and investigate' },
      { type: 'list', ordered: true, items: [
        'Build the tallest tower that can hold a toy.',
        'Test safe objects to see which sink or float.',
        'Create a cardboard-box shop.',
        'Make a paper-chain pattern.',
        'Mix two paint colors and predict the result.',
        'Go on an indoor scavenger hunt for shapes.',
      ] },
      { type: 'callout', tone: 'tip', content: 'Try a simple rhythm: one movement activity, one snack or water break, then one quiet activity.' },
      { type: 'CTA', heading: 'Keep an indoor activity ready', content: 'Get a free printable sample from The Kiddle for the next stuck-inside day.', buttonLabel: 'Get the Free Sample', href: '/#sample-kiddle' },
    ],
  },
  {
    slug: 'why-themed-learning-works-better-for-kids-3-5',
    title: 'Why Themed Learning Works Better for Kids Ages 3–5 (And How to Try It at Home)',
    excerpt:
      'Young children absorb information best when learning is tied to a theme they care about, not disconnected worksheets.',
    seoDescription:
      'Why themed learning works for preschoolers ages 3–5, plus simple ways parents can make learning fun at home.',
    category: 'Learning Science',
    date: '2026-04-18',
    heroImage: '',
    heroImageAlt: '',
    seoKeywords: [
      'themed learning for preschoolers',
      'learning activities for 3–5 year olds',
      'how to make learning fun for toddlers',
    ],
    blocks: [
      { type: 'paragraph', content: 'Most parents assume worksheets equal learning. But child development research tells a different story — young children absorb information best when it\'s connected to something they care about. That\'s the power of themed learning.' },
      { type: 'paragraph', content: 'When a 4-year-old spends a week inside an "Ocean World," they\'re not just coloring fish. They\'re building vocabulary, asking questions, making connections between movement and science, and developing the kind of curiosity that lasts. A puzzle about coral reefs hits differently when it\'s part of a world your child is already living in.' },
      { type: 'paragraph', content: 'At The Kiddle, every workbook is built around one theme — jungle, ocean, space, and more — so every activity, riddle, and experiment deepens the same world. It\'s not random. It\'s intentional.' },
      { type: 'CTA', heading: 'Ready to try themed learning?', content: 'Explore our current workbooks and discover how playful, connected learning keeps kids curious.', buttonLabel: 'Explore The Kiddle', href: '/#pricing' },
    ],
  },
  {
    slug: '10-signs-your-3-5-year-old-is-ready-for-structured-activities',
    title: '10 Signs Your 3–5 Year Old Is Ready for Structured Activities (Without Formal School)',
    excerpt:
      'Your child may already be ready for structured learning through play—without needing a formal classroom setup.',
    seoDescription:
      '10 practical signs your 3–5 year old is ready for structured activities at home, without formal school pressure.',
    category: 'Parent Guide',
    date: '2026-04-17',
    heroImage: '',
    heroImageAlt: '',
    seoKeywords: [
      'activities for 3 year olds at home',
      'preschool learning at home',
      'kindergarten readiness activities',
      'structured play for toddlers',
    ],
    blocks: [
      { type: 'paragraph', content: 'Every parent wonders: is my child ready? The answer is almost always yes — just not in the way school looks. Kids this age are wired for exploration, not sitting still. The key is finding activities that meet them where they are.' },
      { type: 'paragraph', content: 'Signs your child is ready: they ask "why" constantly, they love pretend play, they can follow a two-step instruction, they\'re curious about animals or nature, they enjoy doing things "by themselves." Sound familiar?' },
      { type: 'paragraph', content: 'The Kiddle workbooks are designed for exactly this stage. No reading required. No prep for parents. Just open the book and follow the theme together — or let them lead.' },
      { type: 'CTA', heading: 'Give your child structured play that still feels fun', content: 'Browse The Kiddle\'s themed workbooks for ages 3–5.', buttonLabel: 'Browse Workbooks', href: '/#pricing' },
    ],
  },
  {
    slug: 'free-printable-workbooks-vs-subscription-workbooks',
    title: "Free Printable Workbooks vs. Subscription Workbooks: What's Actually Worth Your Time",
    excerpt:
      'Free printables are convenient, but subscription workbooks can create deeper, more connected learning journeys.',
    seoDescription:
      'Compare free printable workbooks vs subscription workbooks for preschoolers and see what offers better long-term value.',
    category: 'Workbook Comparison',
    date: '2026-04-16',
    heroImage: '',
    heroImageAlt: '',
    seoKeywords: [
      'free printable workbooks for preschoolers',
      'best printable workbooks for kids',
      'preschool workbook subscription',
      'educational printables for toddlers',
    ],
    blocks: [
      { type: 'paragraph', content: 'A quick Pinterest search gives you hundreds of free printables. So why would any parent pay for a workbook subscription? Here\'s the honest answer.' },
      { type: 'paragraph', content: 'Free printables are great for filling 20 minutes. But they\'re random — a letter tracing sheet, a coloring page, a dot-to-dot — with no thread connecting them. Your child does the page and moves on. There\'s no experience, no story, no depth.' },
      { type: 'paragraph', content: 'A well-designed subscription workbook gives your child a journey. Each activity builds on the last. The theme carries meaning. Your child doesn\'t just complete a page — they come back asking for more because they\'re invested in the world they\'re exploring.' },
      { type: 'paragraph', content: 'The Kiddle was built to be the upgrade from the free printable pile. Same convenience, but with intentional design behind every page.' },
      { type: 'CTA', heading: 'See the difference in action', content: 'Discover what a themed workbook experience looks like for your child.', buttonLabel: 'See Themed Workbooks', href: '/#pricing' },
    ],
  },
  {
    slug: 'how-to-keep-a-3-5-year-old-engaged-without-a-screen',
    title: 'How to Keep a 3–5 Year Old Engaged for More Than 10 Minutes (Without a Screen)',
    excerpt:
      'The trick is not harder activities—it is layered activities that create momentum and keep kids curious.',
    seoDescription:
      'How to keep toddlers and preschoolers engaged longer with layered, screen-free activities at home.',
    category: 'Screen-Free Play',
    date: '2026-04-15',
    heroImage: '',
    heroImageAlt: '',
    seoKeywords: [
      'how to keep toddlers engaged',
      'screen free activities for preschoolers',
      'activities for 4 year olds at home',
      'non-screen learning for kids',
    ],
    blocks: [
      { type: 'paragraph', content: 'Every parent knows the struggle. You set up an activity with the best intentions. Eight minutes later, they\'re done and asking for the iPad.' },
      { type: 'paragraph', content: 'The secret isn\'t finding a harder activity — it\'s finding one with more layers. When a child can move through something (first color this, now find it, now act it out, now solve the riddle), they stay engaged because there\'s always a next step. The activity has momentum.' },
      { type: 'paragraph', content: 'This is exactly how The Kiddle workbooks are structured. A single theme is explored through coloring, logic, movement, puzzles, and mini-experiments — so there\'s always something new coming, even within the same session. Parents tell us their kids ask to "do the book" before they\'ve even suggested it.' },
      { type: 'CTA', heading: 'Need your next screen-free activity plan?', content: 'Find your child\'s next themed learning adventure with The Kiddle.', buttonLabel: 'Find Your Adventure', href: '/#pricing' },
    ],
  },
  {
    slug: 'best-preschool-workbooks-2025-what-to-look-for',
    title: 'The Best Preschool Workbooks of 2025 — What to Look for and What to Skip',
    excerpt:
      'A simple framework for choosing workbooks that build thinking, curiosity, and joyful learning—not just busy work.',
    seoDescription:
      'Best preschool workbooks in 2025: what to skip, what to look for, and how to choose engaging learning books for ages 3–5.',
    category: 'Workbook Buying Guide',
    date: '2026-04-14',
    heroImage: '',
    heroImageAlt: '',
    seoKeywords: [
      'best preschool workbooks',
      'best workbooks for 3 year olds',
      'educational workbooks for toddlers',
      'preschool learning books review',
    ],
    blocks: [
      { type: 'paragraph', content: 'Not all workbooks are created equal. If you\'re shopping for your 3–5 year old, here\'s a quick framework to save you time.' },
      { type: 'paragraph', content: 'Skip workbooks that: are just tracing and coloring with no thinking involved, feel like drills, have no connection between activities, or bore you as a parent — because if it bores you, it\'ll bore them faster.' },
      { type: 'paragraph', content: 'Look for workbooks that: mix different types of thinking (visual, physical, logical), build on a single idea across multiple pages, invite questions and conversation, and feel playful rather than academic.' },
      { type: 'paragraph', content: 'The Kiddle was designed with all of this in mind. Every theme — from Jungle Explorer to Ocean World — takes your child through colors, puzzles, movement breaks, logic games, and riddles, all connected to one world they can explore at their own pace.' },
      { type: 'CTA', heading: 'Compare themes and choose the right fit', content: 'Find the workbook style that matches your child\'s curiosity and learning pace.', buttonLabel: 'Compare Themes', href: '/#pricing' },
    ],
  },
]

export function getAllPosts() {
  return blogPosts
}

export function getPostBySlug(slug: string) {
  return blogPosts.find((post) => post.slug === slug)
}

export function getAllCategories() {
  return Array.from(new Set(blogPosts.map((post) => post.category)))
}
